### ISSUE TITLE
config script

### ISSUE THREAD

**Issue by Thatoo** [YunoHost-Apps/conduit_ynh#11]
I'm not an expert but I can't see much relation between [this config file](https://github.com/YunoHost-Apps/conduit_ynh/blob/master/scripts/config) talking about amount, prices, frequency, currency and the matrix server conduit.

**Comment by orhtej2** [comment]
This script was [inherited from example_ynh](https://github.com/YunoHost/example_ynh/blob/master/scripts/config) and does not affect anything given [`config_panel.toml` binds the config for directly](https://github.com/YunoHost-Apps/conduit_ynh/blob/fdc9921f99543640fcfa357aeca143cdacd0f482/config_panel.toml#L15)
