### ISSUE TITLE
Critical vulnerability

### ISSUE THREAD

**Issue by getzze** [YunoHost-Apps/conduit_ynh#35]
From 0.8 release changelog: https://conduit.rs/changelog/
"This release is focused on patching security vulnerabilities. Most notably, there is a CRITICAL vulnerability, which requires an attacker to have an account on your server. Administrators which have untrusted users on their server (e.g. public homeservers) are advised to update immediately or take their homeserver off the internet ASAP."

More info in the changelog.

@ericgaspar  I think this package should be disabled until updated to 0.8.

**Comment by ericgaspar** [comment]
fixed

**Comment by getzze** [comment]
I just tried to update and the checksum don't match:

```
Error: Failed to rollback sources : YunoHost was able to download the asset 'main' (https://gitlab.com/api/v4/projects/famedly%2Fconduit/jobs/artifacts/master/raw/x86_64-unknown-linux-musl?job=artifacts) for conduit, but the asset doesn't match the expected checksum. This could mean that some temporary network failure happened on your server, OR the asset was somehow changed by the upstream maintainer (or a malicious actor?) and YunoHost packagers need to investigate and perhaps update the app manifest to take this change into account.
    Expected sha256 checksum: eafa400feefee2a2117d56a09c891d0c39cbec30520a2422056d7d2dcd00de04
    Downloaded sha256 checksum: ba6825d7108bba124f4dbb39d579a34816d34d635547e898b6e9813ffb04b045
    Downloaded file size: 58M
```

**Comment by rmkni** [comment]
> I just tried to update and the checksum don't match:
> 
> ```
> Error: Failed to rollback sources : YunoHost was able to download the asset 'main' (https://gitlab.com/api/v4/projects/famedly%2Fconduit/jobs/artifacts/master/raw/x86_64-unknown-linux-musl?job=artifacts) for conduit, but the asset doesn't match the expected checksum. This could mean that some temporary network failure happened on your server, OR the asset was somehow changed by the upstream maintainer (or a malicious actor?) and YunoHost packagers need to investigate and perhaps update the app manifest to take this change into account.
>     Expected sha256 checksum: eafa400feefee2a2117d56a09c891d0c39cbec30520a2422056d7d2dcd00de04
>     Downloaded sha256 checksum: ba6825d7108bba124f4dbb39d579a34816d34d635547e898b6e9813ffb04b045
>     Downloaded file size: 58M
> ```

https://github.com/YunoHost-Apps/conduit_ynh/pull/37

**Comment by getzze** [comment]
I could update, thanks!
