### ISSUE TITLE
I'm unable to update the app

### ISSUE THREAD

**Issue by mtyton** [YunoHost-Apps/conduit_ynh#38]
Hi,
I'm on version 0.6.0, unfortunately I'm unable to upgrade my conduit server.
It does not matter if I try to upgrade to 0.8.0 or to 0.7.0 it always fails

I'm running on VPS, here are some logs for context:
https://paste.yunohost.org/raw/ejazerejiv

My problem looks similar to this issue: 
https://github.com/YunoHost-Apps/conduit_ynh/issues/33

**Comment by KodeIn** [comment]
Same problem here ...
[https://paste.yunohost.org/raw/torobeyeci](url)

**Comment by 32bitx64bit** [comment]
can't even install it either.

**Comment by ericgaspar** [comment]
Conduit artifacts are not versioned, when updated upstream it breaks our installation....

**Comment by ericgaspar** [comment]
fixed
