### ISSUE TITLE
failed to install because artefact change

### ISSUE THREAD

**Issue by gwen-lg** [YunoHost-Apps/conduit_ynh#40]
### Describe the bug

The installation of `Conduit` failed because the linked artifact changed and the sha256 no longer match.

Instead of use artifact from next, i could be better to use artifact from release ?

In gitlab, by following link, I have found the url of artifact from release of v0.8.0 :
https://gitlab.com/famedly/conduit/-/jobs/7085149318/artifacts/browse

and direct link for x86_64 and arm64 : 
https://gitlab.com/famedly/conduit/-/jobs/7085149318/artifacts/raw/aarch64-unknown-linux-musl?inline=false
https://gitlab.com/famedly/conduit/-/jobs/7197089162/artifacts/raw/x86_64-unknown-linux-musl?inline=false

I think it's more appropriate to link to tagged/release version than next.
What do you think ?

**Comment by ericgaspar** [comment]
You are right, fixed with #41. But it will break the same but less often

**Comment by ericgaspar** [comment]
fixed
