### ISSUE TITLE
Install failed if an app is installed on domain used for server_name

### ISSUE THREAD

**Issue by gwen-lg** [YunoHost-Apps/conduit_ynh#44]
### Describe the bug

The installation failed with following warning if an app (my_webapp by example) is installed on domain use for `server_name`

WARNING - Failed to provision permissions : Cette URL n'est pas disponible ou est en conflit avec une application existante :
 * domain.tld/ → domain.tld website (my_webapp)

### Context

- Hardware: *dedicated server*
- YunoHost version: 12.2.17.1
- I have access to my server: *Through SSH & through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- Using, or trying to install package version/branch: main

### Steps to reproduce

- get a `domain.tld` with a subdomain `conduit.domain.tld` and setup it on yunohost
- install a my_webapp (by example) on `domaine.tld` root
- tried to install **_Conduit_** on `conduit.domain.tld` for domain and `domain.tld` for `server_name`
The installation failed with this warning :
WARNING - Failed to provision permissions : Cette URL n'est pas disponible ou est en conflit avec une application existante :
 * domain.tld/ → domain.tld website (my_webapp)

### Expected behavior

As Conduit only need `domain.tld` for provide some `/.well-known/matrix/...`, it should'nt conflict with `my_webapp`.

I understand it possibly need a feature in yunohost.

### Logs
WARNING - Failed to provision permissions : Cette URL n'est pas disponible ou est en conflit avec une application existante :
 * domain.tld/ → domain.tld website (my_webapp)

**Comment by tituspijean** [comment]
It should have been fixed by YunoHost/yunohost#1647
