### ISSUE TITLE
Conduwuit?

### ISSUE THREAD

**Issue by Thatoo** [YunoHost-Apps/conduit_ynh#47]
Have you heard of Conduwuit : https://conduwuit.puppyirl.gay/ ?
It sounds much more developed than conduit : https://conduwuit.puppyirl.gay/differences.html

Did anyone try and can compare with conduit?

**Comment by tituspijean** [comment]
Contributions are welcome over at https://github.com/YunoHost-Apps/conduwuit_ynh ;)

Closing, I do not think this is the right place and time to discuss alternatives. 😅
