### ISSUE TITLE
Conduit , problème de connexion avec l'exterieur

### ISSUE THREAD

**Issue by gchilloux** [YunoHost-Apps/conduit_ynh#6]
- Matériel : Ancien PC portable Core-i5
- Version de Yunohost : 11.2.3 (stable)
- Accès : Webadmin et SSH
- Tentative d'installation de Conduit
- Installation à partir du webadmin ou à partir de CLI, même résultat

Une fois l'application installée, je remarque que le service conduit n'est pas démarré.

Dans le fichier /var/www/conduit/conduit.toml
j'ai bien les infos suivantes 
`# Enables registration. If set to false, no users can register on this server.
allow_registration = true

allow_federation = true
allow_check_for_updates = true
`
Autorisant, la création de compte et la fédération.
Si je crée 2 users à partir d'un client comme element.io, pas de problème. les 2 peuvent communiquer entre eux.

Par contre, la fédération ne marche pas. impossible de contacter l'exterieur.

Lorsque je vais sur le site https://federationtester.matrix.org/ et que je rentre le domaine utilisé, j'ai le message d'erreur suivant : 
` Get "https://mon_ip:8448/_matrix/key/v2/server": dial tcp mon_ip:8448: connect: connection refused `
J'ai remplacé mon vrai nom de domaine par mon_ip

Le port 8448 est bien ouvert sur ma box et dans le pare-feu de yunohost.

Lorsque je souhaite discuter avec un contact exterieur, celui ci ne voit pas ma demande de contact et cela me génére de mon côté un salon vide.

https://paste.yunohost.org/suwifibowe.sql

Si quelqu'un a une idée je suis preneur

**Comment by Thatoo** [comment]
This https://github.com/YunoHost-Apps/conduit_ynh/pull/9 will help to invite user, I couldn't before this change, but the invited friend still get an error after accepting the invitation : 
`MatrixError: [502] Failed to make_join via any server`
